apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mineos
  namespace: flux-system
spec:
  interval: 5m
  path: ../../mineos
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: mineos
  timeout: 2m
  wait: true