apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nfs-client-provisioner
  namespace: nfs-provisioner
spec:
  interval: 5m
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      sourceRef:
        kind: HelmRepository
        name: nfs-subdir-external-provisioner
        namespace: nfs-provisioner
      version: "4.0.18"  # pas aan als je wilt
  values:
    nfs:
      server: 192.168.104.100
      path: /volume1/elitedesk-k3s
    storageClass:
      name: nfs-client
      defaultClass: true
      accessModes: [ReadWriteMany]
      reclaimPolicy: Retain
