apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: portainer
  namespace: portainer
spec:
  interval: 30m
  chart:
    spec:
      chart: portainer
      version: 2.27.0
      sourceRef:
        kind: HelmRepository
        name: charts
        namespace: portainer
  values:
    service:
      type: ClusterIP
    ingress:
      enabled: false  # kun je later inschakelen
