apiVersion: v1
kind: Namespace
metadata:
  name: nfs-provisioner
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-client
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.104.100
  share: /volume1/elitedesk-k3s
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
  - vers=4.1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-client-provisioner
  namespace: nfs-provisioner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nfs-client-provisioner
  template:
    metadata:
      labels:
        app: nfs-client-provisioner
    spec:
      containers:
        - name: nfs-client-provisioner
          image: k8s.gcr.io/sig-storage/nfs-subdir-external-provisioner:v4.0.2
          env:
            - name: PROVISIONER_NAME
              value: nfs.csi.k8s.io
            - name: NFS_SERVER
              value: 192.168.104.100
            - name: NFS_PATH
              value: /volume1/elitedesk-k3s