apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-client-provisioner
  namespace: nfs-provisioner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nfs-client-provisioner
  template:
    metadata:
      labels:
        app: nfs-client-provisioner
    spec:
      containers:
        - name: nfs-client-provisioner
          image: k8s.gcr.io/sig-storage/nfs-subdir-external-provisioner:v4.0.2
          env:
            - name: PROVISIONER_NAME
              value: nfs.csi.k8s.io
            - name: NFS_SERVER
              valueFrom:
                configMapKeyRef:
                  name: nfs-config
                  key: NFS_SERVER
            - name: NFS_PATH
              valueFrom:
                configMapKeyRef:
                  name: nfs-config
                  key: NFS_PATH
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
      volumes:
        - name: nfs-client-root
          nfs:
            server: 192.168.104.100     # <-- vaste waarde hier
            path: /volume1/elitedesk-k3s  # <-- vaste waarde hier
