replicaCount: 1

image:
  repository: hexparrot/mineos
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  ports:
    web: 8443
    minecraft: 25565

persistence:
  enabled: true
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 5Gi

env:
  MINEOS_UN: mc
  MINEOS_PW: changeme
