apiVersion: v1
kind: Service
metadata:
  name: {{ include "mineos.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8443
      targetPort: web
      name: web
    - port: 25565
      targetPort: minecraft
      name: minecraft
  selector:
    app: {{ include "mineos.name" . }}
