apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: filebrowser
  namespace: filebrowser
spec:
  interval: 30m
  chart:
    spec:
      chart: filebrowser
      version: 2.32.0
      sourceRef:
        kind: HelmRepository
        name: filebrowser-charts
        namespace: filebrowser
  values:
    persistence:
      enabled: true
      existingClaim: filebrowser-data
    service:
      type: ClusterIP
    ingress:
      enabled: false  # kun je later inschakelen
